name: Token Transformer

on:
  push:
    branches:
      - main
jobs:
  Run_tokens_transformer_and_push_changes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json
  
      - name: Placeholder File
        run: |
          touch output-tokens.json
        working-directory: ${{ github.workspace }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run JavaScript File
        run: |
            node android_converter.js
