name: Token Transformer

on:
  push:
    branches:
      - main
jobs:
  create_and_commit_directory:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Create Directory and Placeholder File
      run: |
        mkdir my_new_directory
        touch my_new_directory/placeholder.txt
      working-directory: ${{ github.workspace }}
   
    - name: Commit and Push Directory
      run: |
        git config --global user.email "andrew-2120@live.com"
        git config --global user.name "Andrew2120"
        git add my_new_directory
        git commit -m "Add my_new_directory"
        git remote set-url origin https://github.com/Andrew2120/fiber-core.git  # Replace USERNAME and REPOSITORY with your GitHub username and repository name
        git push origin main
      env:
        GITHUB_TOKEN: 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
      working-directory: ${{ github.workspace }}
