name: Generate Tokens

on:
  push:
    branches:
      - retail


jobs:
  Run_tokens_transformer_and_push_generated_files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json --excludes '$themes' --excludes '$metadata' --sets component/light --sets component/dark --sets alias --sets global

      - name: Generate Tokens for Kotlin and Swift
        run: node index.js ./output-tokens.json DesignSystem.swift DesignSystem.kt

      - name: Push to Fiber-Android
        env:
          ACCESS_ANDROID: ${{ secrets.ACCESS_ANDROID }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'Andrew2120'
          git config --global user.email 'andrew-2120@live.com'
          git clone -b retail https://user:$ACCESS_ANDROID@github.com/Andrew2120/Fiber-Android2.git Fiber-android-temp
          rm -rf Fiber-android-temp/retail/src/main/java/com/b_labs/retail/DesignSystem.kt
          cp DesignSystem.kt Fiber-android-temp/retail/src/main/java/com/b_labs/retail
          cd Fiber-android-temp
          git add .
          git commit -m "Copy DesignSystem.kt from fiber-core"
          git push
      - name: Push to Fiber-iOS Retail
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          working-directory: ${{ github.workspace }} 
        run: |
          git config user.name 'YousefBtech'
          git config user.email 'yousef.hanafi@btech.com'
          git clone -b retail https://user:$ACCESS_TOKEN@github.com/YousefBtech/fiber-iOS.git fiber-ios-temp
          rm -rf fiber-ios-temp/Sources/Fiber-iOS/DesignSystem.swift
          cp DesignSystem.swift fiber-ios-temp/Sources/Fiber-iOS
          cd fiber-ios-temp
          git status
          git add .
          git commit -m "Copy DesignSystem.swift from fiber-core"
          git push  

     
