name: Token Transformer

on:
  push:
    branches:
      - main
jobs:
  create_and_commit_directory:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Create Directory and Placeholder File
      run: |
        mkdir my_new_directory
        touch my_new_directory/placeholder.txt  # Create a placeholder file
      working-directory: ${{ github.workspace }}
    
    - name: Commit and Push Directory
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add my_new_directory
        git commit -m "Add my_new_directory"
        git push
      working-directory: ${{ github.workspace }}
