name: Generate Tokens

on:
  push:
    branches:
      - deel


jobs:
  Run_tokens_transformer_and_push_generated_files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json --excludes '$themes' --excludes '$metadata' --sets component/light --sets component/dark --sets alias --sets global

      - name: Generate Tokens for Kotlin and Swift
        run: node index.js ./output-tokens.json DesignSystem.swift DesignSystem.kt

      - name: Push to Fiber-Android
        env:
          ACCESS_ANDROID: ${{ secrets.ACCESS_ANDROID }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'Andrew2120'
          git config --global user.email 'andrew-2120@live.com'
          git clone deel https://user:$ACCESS_ANDROID@github.com/Andrew2120/Fiber-android.git Fiber-android-temp
          rm -rf Fiber-android-temp/fiber/src/main/java/com/b_labs/fiber/theme/DesignSystem.kt
          cp DesignSystem.kt Fiber-android-temp/fiber/src/main/java/com/b_labs/fiber/theme
          cd Fiber-android-temp
          git add .
          git commit -m "Copy DesignSystem.kt from fiber-core"
          git push target-repo HEAD:deel

     
