name: Generate Tokens

on:
  push:
    branches:
      - mylo


jobs:
  Run_tokens_transformer_and_push_generated_files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install token-transformer
        run: npm install token-transformer

      - name: Generate Tokens for Kotlin and Swift
        run: |
          ls
          node index.js ./tokens.json DesignSystem.swift DesignSystem.kt fiber_mylo

      - name: Push to Fiber-iOS Mylo
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'YousefBtech'
          git config --global user.email 'yousef.hanafi@btech.com'
          git clone https://user:$ACCESS_TOKEN@github.com/YousefBtech/fiber-iOS.git fiber-ios-temp
          rm -rf fiber-ios-temp/Sources/FiberCore/DesignSystemTypes.swift
          cp DesignSystemTypes.swift fiber-ios-temp/Sources/FiberCore/
          rm -rf fiber-ios-temp/Sources/Fibermylo/DesignSystemValues.swift
          cp DesignSystemValues.swift fiber-ios-temp/Sources/FiberMylo/
          cd fiber-ios-temp
          git add .
          git commit -m "Copy DesignSystem.swift from fiber-core"
          git push  
      

      - name: Push to Fiber-Android Mylo
        env:
          ACCESS_ANDROID: ${{ secrets.ACCESS_ANDROID }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'Andrew2120'
          git config --global user.email 'andrew-2120@live.com'
          git clone https://user:$ACCESS_ANDROID@github.com/Andrew2120/f-android.git Fiber-android-temp
          
          rm -rf Fiber-android-temp/fiber-mylo/src/main/java/com/b_labs/fiber_mylo/DesignSystemValues.kt
          cp DesignSystemValues.kt Fiber-android-temp/fiber-mylo/src/main/java/com/b_labs/fiber_mylo

          rm -rf Fiber-android-temp/HIComponents/src/main/java/com/b_labs/hicomponents/theme/DesignSystemTypes.kt
          cp DesignSystemTypes.kt Fiber-android-temp/HIComponents/src/main/java/com/b_labs/fiber_tokens
          
          cd Fiber-android-temp
          git add .
          git commit -m "Copy DesignSystem.kt from fiber-core"
          git push
      
