name: Token Transformer

on:
  push:
    branches:
      - main
jobs:
  Run_tokens_transformer_and_push_changes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json
  
      - name: Placeholder File
        run: |
          touch output-tokens.json
        working-directory: ${{ github.workspace }}
      - name: Install Quicktype
        run: npm install -g quicktype
        
      - name: Run Quicktype
        run: quicktype output-tokens.json -o Tokens.kt

      - name: Commit and Push Directory
        run: |
          git config --global user.email "andrew-2120@live.com"
          git config --global user.name "Andrew2120"
          git add Tokens.kt
          git commit -m "update tokens"
          git remote set-url origin https://github.com/Andrew2120/fiber-core.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}
