name: Token Transformer

on:
  push:
    branches:
      - main
jobs:
  Run_tokens_transformer_and_push_changes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json
  
      - name: Placeholder File
        run: |
          touch output-tokens.json
        working-directory: ${{ github.workspace }}
      - name: Install Quicktype
        run: npm install -g quicktype
        
      - name: Run Quicktype
        run: quicktype output-tokens.json -o Tokens.kt
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run JavaScript File
        run: |
            node script.js


      - name: Commit and Push Directory
        run: |
          git config --global user.email "andrew-2120@live.com"
          git config --global user.name "Andrew2120"
          git add Tokens.kt output-tokens.json
          git commit -m "update tokens"
          git remote set-url origin https://github.com/Andrew2120/fiber-core.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}
        
      - name: creates output
        run: echo "This is some content for the text file" > example.txt
         
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'example'
          destination-github-username: 'Anddrew2120'
          destination-repository-name: 'Andrew2120/FiberA'
          user-email: andrew-2120@live.com
          target-branch: main
