name: Token Transformer

on:
  push:
    branches:
      - main

jobs:
  transform-tokens:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer fiber-core/tokens.json fiber-core/output-tokens.json


      - name: Upload Output Tokens as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output-tokens
          path: fiber-core/output-tokens.json
