name: Token Transformer

on:
  push:
    branches:
      - main

jobs:
  transform-tokens:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Andrew2120"
          git config --global user.email "andrew-2120@live.com"

      - name: Make Changes
        run: |
          # Make your changes here, e.g., echo "New content" > file.txt
          git add .
          git commit -m "Auto commit by GitHub Actions"
          git push

      - name: Push changes
        run: git push
