name: Token Transformer

on:
  push:
    branches:
      - main
permissions:
  contents: write      
jobs:
  Run_tokens_transformer_and_push_changes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json
        
      - name: Placeholder File
        run: |
          touch output-tokens.json
        working-directory: ${{ github.workspace }}
         
      - name: Commit and Push Directory
        run: |
          git config --global user.email "andrew-2120@live.com"
          git config --global user.name "Andrew2120"
          git add output-tokens.json
          git commit -m "update tokens"
          git remote set-url origin https://github.com/Andrew2120/fiber-core.git  # Replace USERNAME and REPOSITORY with your GitHub username and repository name
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}
        


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run JavaScript File
        run: 
           node android_converter.js
      - name: Placeholder File
        run: |
          touch BTokens.kt
        working-directory: ${{ github.workspace }}
      - name: Push to Another Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
          git config --local user.email "Andrew-2120@live.com"
          git config --local user.name "Andrew"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            repository: Andrew2120/FiberA
            force: true

