name: Generate Tokens

on:
  push:
    branches:
      - main
jobs:
  Run_tokens_transformer_and_push_generated_files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json --excludes '$themes' --excludes '$metadata' --sets component/light --sets component/dark --sets alias --sets global

      - name: Generate Tokens for Kotlin and Swift
        run: node index.js ./output-tokens.json DesignSystem.swift DesignSystem.kt

      - name: Placeholder File
        run: |
          touch output-tokens.json
          touch DesignSystem.kt
          touch DesignSystem.swift
        working-directory: ${{ github.workspace }}
         
      - name: Commit and Push Directory
        run: |
          git config --global user.email "andrew-2120@live.com"
          git config --global user.name "Andrew2120"
          git add output-tokens.json DesignSystem.swift DesignSystem.kt
          git commit -m "update tokens"
          git remote set-url origin https://github.com/Andrew2120/fiber-core.git  # Replace USERNAME and REPOSITORY with your GitHub username and repository name
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }}  
      - name: Push to Fiber-iOS
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'YousefBtech'
          git config --global user.email 'yousef.hanafi@btech.com'
          git clone https://user:$ACCESS_TOKEN@github.com/YousefBtech/fiber-iOS.git fiber-ios-temp
          rm -rf fiber-ios-temp/Sources/Fiber-iOS/DesignSystem.swift
          cp DesignSystem.swift fiber-ios-temp/Sources/Fiber-iOS
          cd fiber-ios-temp
          git add .
          git commit -m "Copy DesignSystem.swift from fiber-core"
          echo "git commit done"
          git push         
      
