name: Token Transformer

on:
  push:
    branches:
      - main
jobs:
  create_directory:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Create Directory
      run: |
        mkdir my_new_directory
      working-directory: ${{ github.workspace }}
    
    - name: List Contents
      run: |
        ls -l
      working-directory: ${{ github.workspace }}
