name: Generate Tokens

on:
  push:
    branches:
      - deel


jobs:
  Run_tokens_transformer_and_push_generated_files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install token-transformer
        run: npm install token-transformer

      - name: Transform tokens
        run: npx token-transformer tokens.json output-tokens.json --excludes '$themes' --excludes '$metadata' --sets component/light --sets component/dark --sets alias --sets global

      - name: Generate Tokens for Kotlin and Swift
        run: node index.js ./output-tokens.json DesignSystem.swift DesignSystem.kt

      - name: Push to Fiber-iOS deel
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          working-directory: ${{ github.workspace }} 
        run: |
          git config user.name 'YousefBtech'
          git config user.email 'yousef.hanafi@btech.com'
          git clone -b retail https://user:$ACCESS_TOKEN@github.com/YousefBtech/fiber-core2.git fiber-ios-temp
          cp DesignSystemValues.swift fiber-ios-temp/
          cp DesignSystemTypes.swift fiber-ios-temp/
          cd fiber-ios-temp
          git add .
          git commit -m "Copy DesignSystem.swift from fiber-core"
          git push  
      

      - name: Push to Fiber-Android Deel
        env:
          ACCESS_ANDROID: ${{ secrets.ACCESS_ANDROID }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'Andrew2120'
          git config --global user.email 'andrew-2120@live.com'
          git clone https://user:$ACCESS_ANDROID@github.com/Andrew2120/f-android.git Fiber-android-temp
          
          rm -rf Fiber-android-temp/fiber-deel/src/main/java/com/b_labs/fiber_deel/DesignSystemValues.kt
          cp DesignSystemValues.kt Fiber-android-temp/fiber-deel/src/main/java/com/b_labs/fiber_deel
          
          rm -rf Fiber-android-temp/fiber-tokens/src/main/java/com/b_labs/fiber_tokens/DesignSystemTypes.kt
          cp DesignSystemTypes.kt Fiber-android-temp/fiber-tokens/src/main/java/com/b_labs/fiber_tokens
          
          cd Fiber-android-temp
          git add .
          git commit -m "Copy DesignSystem.kt from fiber-core"
          git push
      
